### PR TITLE
Fixes #200: Reading empty query sets fails due to schema inference

### LINKED ISSUE #200: Reading empty query sets fails due to schema inference
See screenshot.

Probably we're trying to sample the result and that's failing, because there are no results.

Screen Shot 2020-09-28 at 8 16 31 AM

### PR DESCRIPTION
**Pull request by utnaf**
Fixes #200 

We had to deal with some missing data from the API across different versions of Neo4j. 
It has been solved but it's rather unstable for Neo4j 4.0 and 3.5, and requires additional testing. Test cases has been added but I think we might miss something.

This also solves the returned column order issue.

### CODE REVIEW

File: src/main/scala/org/neo4j/spark/service/SchemaService.scala [hunk 1]
```diff
@@ -13,6 +13,8 @@ import org.neo4j.spark.service.SchemaService.{cypherToSparkType, normalizedClass
 import org.neo4j.spark.util.Neo4jImplicits.{CypherImplicits, EntityImplicits}
 import org.neo4j.spark.util.{Neo4jUtil, ValidationUtil}
 import org.neo4j.spark.{DriverCache, Neo4jOptions, OptimizationType, QueryType, SchemaStrategy}
+import org.json4s._
+import org.json4s.jackson.JsonMethods._
```
Comment (conker84) [inline src/main/scala/org/neo4j/spark/service/SchemaService.scala]: they seem unused can you please remove them?

File: src/main/scala/org/neo4j/spark/service/SchemaService.scala [hunk 2]
```diff
@@ -190,7 +192,40 @@ class SchemaService(private val options: Neo4jOptions, private val driverCache:
...
+        case "EagerAggregation" => lastChild.identifiers().asScala.toArray
+        case "ProcedureCall" => plan.identifiers().asScala.toArray
+        case _ =>
+          val expressions = lastChild.arguments().get("Expressions").asString()
+
+          val firstLevelExpressions = "\\{(.*?)}".r.replaceAllIn(expressions.substring(1,expressions.length-1),"_")
+
+          "([^,:]*?):".r.findAllMatchIn(firstLevelExpressions).map(_.group(1).trim).toArray
+      }
+    }
```
Comment (conker84) [inline src/main/scala/org/neo4j/spark/service/SchemaService.scala]: can we extract it into a method?

File: src/main/scala/org/neo4j/spark/service/SchemaService.scala [hunk 3]
```diff
@@ -190,7 +192,40 @@ class SchemaService(private val options: Neo4jOptions, private val driverCache:
...
+
+    val sortedStructFields = if (structFields.isEmpty) {
+      columns.map(StructField(_, DataTypes.StringType))
+    } else {
+      columns.map(c => structFields.find(_.name.quote().equals(c.quote())).get)
+    }
```
Comment (conker84) [inline src/main/scala/org/neo4j/spark/service/SchemaService.scala]: what happens if columns is empty? can we just use`structFields`?

File: src/main/scala/org/neo4j/spark/service/SchemaService.scala [hunk 4]
```diff
@@ -190,7 +192,40 @@ class SchemaService(private val options: Neo4jOptions, private val driverCache:
...
+          val expressions = lastChild.arguments().get("Expressions").asString()
+
+          val firstLevelExpressions = "\\{(.*?)}".r.replaceAllIn(expressions.substring(1,expressions.length-1),"_")
+
+          "([^,:]*?):".r.findAllMatchIn(firstLevelExpressions).map(_.group(1).trim).toArray
+      }
+    }
+
+    val sortedStructFields = if (structFields.isEmpty) {
+      columns.map(StructField(_, DataTypes.StringType))
```
Comment (conker84) [inline src/main/scala/org/neo4j/spark/service/SchemaService.scala]: please add a comment highlighting that we want to return an empty df with the requested columns

File: src/test/scala/org/neo4j/spark/DataSourceReaderTSE.scala [hunk 5]
```diff
@@ -1097,6 +1097,74 @@ class DataSourceReaderTSE extends SparkConnectorScalaBaseTSE {
...
 
+  @Test
+  def testEmptyDataset(): Unit = {
+    val df = ss.read
+      .format(classOf[DataSource].getName)
+      .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
+      .option("query", "MATCH (e:ID_DO_NOT_EXIST) RETURN id(e) as f, 1 as g")
+      .load
+
+    df.show()
```
Comment (conker84) [inline src/test/scala/org/neo4j/spark/DataSourceReaderTSE.scala]: please test the columns with `df.columns` and the count with `df.count`

File: src/test/scala/org/neo4j/spark/DataSourceReaderTSE.scala [hunk 6]
```diff
@@ -1097,6 +1097,74 @@ class DataSourceReaderTSE extends SparkConnectorScalaBaseTSE {
...
+          override def execute(tx: Transaction): ResultSummary = tx.run("CREATE (i1:Instrument{name: 'Drums', id: 1}), (i2:Instrument{name: 'Guitar', id: 2})").consume()
+        })
+
+    val df = ss.read
+      .format(classOf[DataSource].getName)
+      .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
+      .option("query", "MATCH (i:Instrument) RETURN id(i) as internal_id, i.id as id, i.name as name, i.name")
+      .load
+
+    assertEquals(1L, df.collectAsList().get(0).get(1))
```
Comment (conker84) [inline src/test/scala/org/neo4j/spark/DataSourceReaderTSE.scala:1124]: please test the column order by using `df.columns`

File: src/test/scala/org/neo4j/spark/DataSourceReaderTSE.scala [hunk 7]
```diff
@@ -1097,6 +1097,74 @@ class DataSourceReaderTSE extends SparkConnectorScalaBaseTSE {
...
+        })
+
+    ss.read.format(classOf[DataSource].getName)
+      .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
+      .option("query",
+        """MATCH (p:Person)-[b:BOUGHT]->(pr:Product)
+          |RETURN id(p) AS personId, id(pr) AS productId, {quantity: b.quantity, when: b.when} AS map, "some string" as someString, {anotherField: "201"} as map2""".stripMargin)
+      .option("schema.strategy", "string")
+      .load()
+      .show()
```
Comment (conker84) [inline src/test/scala/org/neo4j/spark/DataSourceReaderTSE.scala]: did we lose the assertions here?

File: src/test/scala/org/neo4j/spark/DataSourceReaderTSE.scala [hunk 8]
```diff
@@ -1097,6 +1097,74 @@ class DataSourceReaderTSE extends SparkConnectorScalaBaseTSE {
...
+  @Test
+  def testComplexReturnStatementNoValues(): Unit = {
+    ss.read.format(classOf[DataSource].getName)
+      .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
+      .option("query",
+        """MATCH (p:Person)-[b:BOUGHT]->(pr:Product)
+          |RETURN id(p) AS personId, id(pr) AS productId, {quantity: b.quantity, when: b.when} AS map, "some string" as someString, {anotherField: "201", and: 1} as map2""".stripMargin)
+      .option("schema.strategy", "string")
+      .load()
+      .show()
```
Comment (conker84) [inline src/test/scala/org/neo4j/spark/DataSourceReaderTSE.scala]: did we lost the assertions here?

**Review by conker84 — CHANGES_REQUESTED** [review]
@utnaf thank you so much please look at my comments

File: src/main/scala/org/neo4j/spark/service/SchemaService.scala (hunk 3 above)
Comment (utnaf) [reply src/main/scala/org/neo4j/spark/service/SchemaService.scala]: Two scenarios here:
- both structFields and columns are empty, then this should fail I guess
- structFields is not empty and columns is empty, this is weird af

I would raise an exception in both cases @conker84

**Comment by moxious** [comment]
I've reviewed the code at the high level.   This does answer the need so I'm an approve.  When Andrea is satisfied that code review changes have been made, LGTM and you can merge.

**Comment by utnaf** [comment]
Edit: sorting columns issue is solved just for Neo4j 4.1. Explain command data we retrieve from <=4.0 are not sorted like in the RETURN statement.

File: doc/docs/modules/ROOT/pages/faq.adoc [hunk 9]
```diff
@@ -56,3 +56,8 @@ all the values for that field will be casted to String. This because Spark is no
 and need each column to always have the same type.
 
 You can read more <<quickstart.adoc#bookmark-read-known-problem, here>>.
+
+== The returned columns are not in the same ordere as I specified in the query
+
+Unfortunately this is a known issue and is there for Neo4j 3.* and Neo4j 4.0.
+With Neo4j 4.1+ you will get the same order as specified in the return statement.
```
Comment (utnaf) [inline doc/docs/modules/ROOT/pages/faq.adoc]: @moxious please note this

Comment (moxious) [reply doc/docs/modules/ROOT/pages/faq.adoc]: Understood!  And it's perfect to put it into a FAQ like this.   But since you are drawing my attention, "order" doesn't have an extra e at the end of the word.  :)

File: src/test/scala/org/neo4j/spark/DataSourceReaderNeo4j41xTSE.scala [hunk 10]
```diff
@@ -0,0 +1,92 @@
...
+import org.apache.spark.sql.DataFrame
+import org.junit.Assert.assertEquals
+import org.junit.{Assume, BeforeClass, Test}
+import org.neo4j.driver.summary.ResultSummary
+import org.neo4j.driver.{SessionConfig, Transaction, TransactionWork}
+
+object DataSourceReaderNeo4j41xTSE {
+  @BeforeClass
+  def checkNeo4jVersion() {
+    Assume.assumeTrue(TestUtil.neo4jVersion().startsWith("4.1"))
```
Comment (conker84) [inline src/test/scala/org/neo4j/spark/DataSourceReaderNeo4j41xTSE.scala]: I would change this in this way'
```suggestion
    val neo4jVersion = TestUtil.neo4jVersion()
    Assume.assumeTrue(!neo4jVersion.startsWith("3.5") && !neo4jVersion.startsWith("4.0"))
```

in this way should work also with newer releases such as 4.2 and so on, otherwise we need to clone the test for every new Neo4j version.

WDYT?

**Review by conker84 — CHANGES_REQUESTED** [review]
@utnaf thank a lot! please look at my last comment!

File: src/test/scala/org/neo4j/spark/DataSourceReaderNeo4j41xTSE.scala (hunk 10 above)
Comment (utnaf) [reply src/test/scala/org/neo4j/spark/DataSourceReaderNeo4j41xTSE.scala]: Makes totally sense! On it

**Comment by conker84** [comment]
@utnaf thanks a lot!
