### PR TITLE
fixes #357: transformed isValidQuery severity from ERROR  to DEBUG

### LINKED ISSUE #357: ERROR Neo4jDataWriter: Cannot commit the transaction because: Expected parameter(s): event
## Expected Behavior (Mandatory)
My python code:
```
query = """MATCH (user1:Person{uid: $event.fuid}),(user2:Person{uid: $event.suid}) CREATE (user1)-[:FOLLOW{follow_time: $event.ftime}]->(user2)"""


follow_df\
    .filter("fuid_flag = true").write \
    .format("org.neo4j.spark.DataSource") \
    .mode("Append") \
    .option("url", "bolt://192.168.1.36:7687") \
    .option("authentication.type", "basic") \
    .option("authentication.basic.username", "neo4j") \
    .option("authentication.basic.password", "maker123") \
    .option("query", query) \
    .save()
```

## Actual Behavior (Mandatory)
I got a crash log:
```
with query: WITH $scriptResult AS scriptResult
UNWIND $events AS event
MATCH (user1:Person{uid: $event.fuid}),(user2:Person{uid: $event.suid}) CREATE (user1)-[:FOLLOW{follow_time: $event.ftime}]->(user2)


21/05/24 18:19:32 ERROR Neo4jDataWriter: Cannot commit the transaction because: Expected parameter(s): event
21/05/24 18:19:32 ERROR Utils: Aborting task
org.neo4j.driver.exceptions.ClientException: Expected parameter(s): event
        at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
        at org.neo4j.driver.internal.InternalTransaction.commit(InternalTransaction.java:39)
        at org.neo4j.spark.writer.BaseDataWriter.writeBatch(BaseDataWriter.scala:73)
        at org.neo4j.spark.writer.BaseDataWriter.write(BaseDataWriter.scala:39)
        at org.neo4j.spark.writer.Neo4jDataWriter.write(Neo4jDataWriter.scala:9)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$1(WriteToDataSourceV2Exec.scala:416)
        at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1473)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:452)
        at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:360)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: org.neo4j.driver.exceptions.ClientException: Transaction can't be committed. It has been rolled back either because of an error or explicit termination
                at org.neo4j.driver.internal.async.UnmanagedTransaction.doCommitAsync(UnmanagedTransaction.java:249)
                at org.neo4j.driver.internal.async.UnmanagedTransaction.lambda$commitAsync$1(UnmanagedTransaction.java:172)
                at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
                at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
                at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
                at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
                at org.neo4j.driver.internal.handlers.pulln.AutoPullResponseHandler.failSummaryFuture(AutoPullResponseHandler.java:312)
                at org.neo4j.driver.internal.handlers.pulln.AutoPullResponseHandler.handleFailure(AutoPullResponseHandler.java:126)
                at org.neo4j.driver.internal.handlers.pulln.AutoPullResponseHandler.lambda$installRecordAndSummaryConsumers$1(AutoPullResponseHandler.java:105)
                at org.neo4j.driver.internal.handlers.pulln.BasicPullResponseHandler.complete(BasicPullResponseHandler.java:219)
                at org.neo4j.driver.internal.handlers.pulln.BasicPullResponseHandler.completeWithFailure(BasicPullResponseHandler.java:109)
                at org.neo4j.driver.internal.handlers.pulln.BasicPullResponseHandler$State$3.onFailure(BasicPullResponseHandler.java:345)
                at org.neo4j.driver.internal.handlers.pulln.BasicPullResponseHandler.onFailure(BasicPullResponseHandler.java:82)
                at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleIgnoredMessage(InboundMessageDispatcher.java:144)
                at org.neo4j.driver.internal.messaging.common.CommonMessageReader.unpackIgnoredMessage(CommonMessageReader.java:88)
                at org.neo4j.driver.internal.messaging.common.CommonMessageReader.read(CommonMessageReader.java:62)
                at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
                at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
                at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
                at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
                at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                ... 1 more

```

## Specifications (Mandatory)

Currently used versions

### Versions

- Spark: PySpark 3.1.1
- Python: 3.7.10
- Neo4j: 4.2.6
- Neo4j Connector: neo4j-connector-apache-spark_2.12-4.0.1_for_spark_3.jar

### PR DESCRIPTION
**Pull request by utnaf**
fixes #357

isValidQuery exception now logs a DEBUG log instead of an ERROR log only if DEBUG is enabled.

### CODE REVIEW

File: common/src/main/scala/org/neo4j/spark/service/SchemaService.scala [hunk 1]
```diff
@@ -426,7 +426,9 @@ class SchemaService(private val options: Neo4jOptions, private val driverCache:
     expectedQueryTypes.size == 0 || expectedQueryTypes.contains(queryType)
   } catch {
     case e: Throwable => {
-      log.error("Query not compiled because of the following exception:", e)
+      if (log.isDebugEnabled) {
+        log.error("Query not compiled because of the following exception:", e)
```
Comment (conker84) [inline common/src/main/scala/org/neo4j/spark/service/SchemaService.scala]:
```suggestion
        log.debug("Query not compiled because of the following exception:", e)
```

**Review by conker84 — CHANGES_REQUESTED** [review]

File: common/src/main/scala/org/neo4j/spark/service/SchemaService.scala (hunk 1 above)
Comment (utnaf) [reply common/src/main/scala/org/neo4j/spark/service/SchemaService.scala]: of course
