### PR TITLE
fixes #503: Not able to Insert Neo4j Map Data type using the neo4j-spark connector

### LINKED ISSUE #503: Not able to Insert Neo4j Map Data type using the neo4j-spark connector
### Versions
like #315 

- Spark: 3.3.2
- Scala: 2.12
- Neo4j: neo4j-community-5.7.0
- Neo4j Connector:  neo4j-connector-apache-spark_2.12-4.0.1_for_spark_3.jar
- **Pyspark**
## Additional information
My neo4jDF printschema output

```markdown
root
 |-- id: string (nullable = true)
 |-- time: long (nullable = true)
 |-- table: map (nullable = true)
 |    |-- key: string
 |    |-- value: map (valueContainsNull = true)
 |    |    |-- key: string
 |    |    |-- value: string (valueContainsNull = true)
```

and get the error like this:
```markdown
Caused by: org.neo4j.driver.exceptions.ClientException: Unable to convert org.apache.spark.sql.catalyst.expressions.UnsafeMapData to Neo4j Value.
	at org.neo4j.driver.Values.value(Values.java:134)
	at org.neo4j.driver.Values.value(Values.java:297)
	at org.neo4j.driver.Values.value(Values.java:119)
	at org.neo4j.spark.util.Neo4jUtil$.convertFromSpark(Neo4jUtil.scala:210)
	at org.neo4j.spark.service.Neo4jWriteMappingStrategy.$anonfun$query$1(MappingService.scala:123)
	at org.neo4j.spark.service.Neo4jWriteMappingStrategy.$anonfun$query$1$adapted(MappingService.scala:121)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.neo4j.spark.service.Neo4jWriteMappingStrategy.query(MappingService.scala:121)
	at org.neo4j.spark.service.Neo4jWriteMappingStrategy.node(MappingService.scala:30)
	at org.neo4j.spark.service.Neo4jWriteMappingStrategy.node(MappingService.scala:18)
	at org.neo4j.spark.service.MappingService.convert(MappingService.scala:230)
	at org.neo4j.spark.writer.BaseDataWriter.write(BaseDataWriter.scala:37)
	at org.neo4j.spark.writer.Neo4jDataWriter.write(Neo4jDataWriter.scala:9)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$1(WriteToDataSourceV2Exec.scala:442)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1538)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:480)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:381)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

```

### PR DESCRIPTION
**Pull request by conker84**
fixes #503

- [x] Fixed the issue
- [x] Added a test

### CODE REVIEW

File: common/src/test/scala/org/neo4j/spark/util/Neo4jUtilTest.scala [hunk 1]
```diff
@@ -1,11 +1,29 @@
...
   def testSafetyCloseShouldNotFailWithNull(): Unit = {
     Neo4jUtil.closeSafety(null)
   }
+
+  @Test
+  def testFlattenMap(): Unit = {
+    val input: java.util.Map[String, AnyRef] = Map(
+      "foo" -> "bar",
+      "key" -> Map(
+        "innerKey" -> Map("innnerKey2" -> "value").asJava
```
Comment (fbiville) [inline common/src/test/scala/org/neo4j/spark/util/Neo4jUtilTest.scala]:
```suggestion
        "innerKey" -> Map("innerKey2" -> "value").asJava
```

File: common/src/test/scala/org/neo4j/spark/util/Neo4jUtilTest.scala [hunk 2]
```diff
@@ -1,11 +1,29 @@
...
+      ).asJava
+    ).asJava
+    val expected = Map(
+      "foo" -> "bar",
+      "key.innerKey.innnerKey2" -> "value"
```
Comment (fbiville) [inline common/src/test/scala/org/neo4j/spark/util/Neo4jUtilTest.scala]:
```suggestion
      "key.innerKey.innerKey2" -> "value"
```

File: common/src/main/scala/org/neo4j/spark/util/Neo4jUtil.scala [hunk 3]
```diff
@@ -220,13 +220,15 @@ object Neo4jUtil {
...
-                 prefix: String = ""): java.util.Map[String, AnyRef] = map.asScala.flatMap(t => {
-    val key: String = if (prefix != "") s"${prefix.quote()}.${t._1.quote()}" else t._1.quote()
-    t._2 match {
-      case nestedMap: Map[String, AnyRef] => flattenMap(nestedMap.asJava, key).asScala.toSeq
-      case _ => Seq((key, t._2))
-    }
-  })
+                 prefix: String = ""): java.util.Map[String, AnyRef] = map.asScala
+    .flatMap(t => {
+      val key: String = if (prefix != "") s"${prefix}.${t._1}" else t._1.quote()
```
Comment (fbiville) [inline common/src/main/scala/org/neo4j/spark/util/Neo4jUtil.scala]: what happens if you try to flatten this (denoting in JSON):
```json
{
    "my": {"inner": {"key": 42424242}},
    "my": {"inner.key": 424242},
    "my.inner": {"key": 4242},
    "my.inner.key": 42
}
```
?

**Review by fbiville — CHANGES_REQUESTED** [review]

File: common/src/main/scala/org/neo4j/spark/util/Neo4jUtil.scala (hunk 3 above)
Comment (conker84) [reply common/src/main/scala/org/neo4j/spark/util/Neo4jUtil.scala]: The example has already a collision, with two `my`, I used this:
```json
{
    "my": {"inner": {"key": 42424242}, "inner.key": 424242},
    "my.inner": {"key": 4242},
    "my.inner.key": 42
}
```

File: common/src/main/scala/org/neo4j/spark/service/MappingService.scala [hunk 4]
```diff
@@ -122,10 +125,22 @@ class Neo4jWriteMappingStrategy(private val options: Neo4jOptions)
...
+            val scalaMap = map.asMap().asScala.toMap
+            val dupKeys = scalaMap.flattenKeys(field.name)
+              .groupBy(identity)
+              .collect { case (x, List(_,_,_*)) => x }
+            if (dupKeys.nonEmpty) {
+              logWarning(
+                s"""
+                   |The field `${field.name}` which has a map {${scalaMap.mkString(", ")}}
+                   |contains the following duplicated keys: [${dupKeys.mkString(", ")}],
+                   |you will loose information stored in these keys
```
Comment (fbiville) [inline common/src/main/scala/org/neo4j/spark/service/MappingService.scala]:
```suggestion
                   |you will lose some of the values associated with these duplicate keys
```

File: common/src/main/scala/org/neo4j/spark/util/Neo4jImplicits.scala [hunk 5]
```diff
@@ -198,4 +200,31 @@ object Neo4jImplicits {
     def groupByCols(): Array[Expression] = ReflectionUtils.groupByCols(aggregation)
   }
 
+  implicit class MapImplicit[K, V](map: Map[String, V]) {
+    def flattenMap(prefix: String = ""): Map[String, AnyRef] = {
```
Comment (fbiville) [inline common/src/main/scala/org/neo4j/spark/util/Neo4jImplicits.scala]:
```suggestion
    def flatten(prefix: String = ""): Map[String, AnyRef] = {
```

File: common/src/main/scala/org/neo4j/spark/service/MappingService.scala (hunk 4 above)
Comment (fbiville) [reply common/src/main/scala/org/neo4j/spark/service/MappingService.scala]: shall this warning be logged in the implicit directly instead? I'm not sure

File: common/src/main/scala/org/neo4j/spark/service/MappingService.scala [hunk 6]
```diff
@@ -122,10 +125,22 @@ class Neo4jWriteMappingStrategy(private val options: Neo4jOptions)
...
         val neo4jValue = Neo4jUtil.convertFromSpark(seq(i), field)
         neo4jValue match {
-          case map: MapValue => Neo4jUtil.flattenMap(map.asMap(), field.name)
-            .asScala
-            .map(t => (t._1, Values.value(t._2)))
-            .toSeq
+          case map: MapValue =>
+            val scalaMap = map.asMap().asScala.toMap
+            val dupKeys = scalaMap.flattenKeys(field.name)
+              .groupBy(identity)
```
Comment (fbiville) [inline common/src/main/scala/org/neo4j/spark/service/MappingService.scala]: maybe groupBy identity + transform each list into its size + filter size > 1?

File: common/src/test/scala/org/neo4j/spark/util/Neo4jImplicitsTest.scala [hunk 7]
```diff
@@ -141,4 +144,52 @@ class Neo4jImplicitsTest {
...
+        "inner.key" -> 424242
+      ),
+      "my.inner" -> Map("key" -> 4242).asJava,
+      "my.inner.key" -> 42
+    )
+    val expected = Map(
+      "my.inner.key" -> 42
+    )
+    val actual = input.flattenMap()
+    Assert.assertEquals(expected, actual)
```
Comment (fbiville) [inline common/src/test/scala/org/neo4j/spark/util/Neo4jImplicitsTest.scala:178]: (this comment is entirely optional)

the assertion only works because the `ListMap` iterator order follows the declaration order, right?
maybe a more general test would test the flattening of a regular hash map and

1. check the resulting keys
2. check the values as one of the possible candidate (sth like `42 in [42, 4242, 424242, 424242]` in pseudo-code)

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 8]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+val data = Seq(
+  ("Foo", 1, Map("inner" -> Map("key" -> "innerValue"))),
+  ("Bar", 2, Map("inner" -> Map("key" -> "innerValue1"))),
+).toDF("id", "time", "table")
+
+data.write
+  .mode(SaveMode.Append)
+  .format(classOf[DataSource].getName)
+  .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
+  .option("labels", ":MyNodeWithMapFlattend")
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]:
```suggestion
  .option("labels", ":MyNodeWithFlattenedMap")
```

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 9]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+  .save()
+----
+
+In Neo4j for the nodes with label `MyNodeWithMapFlattend` you'll find this information stored:
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]:
```suggestion
In Neo4j for the nodes with label `MyNodeWithFlattenedMap` you'll find this information stored:
```

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 10]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+
+----
+MyNodeWithMapFlattend {
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]:
```suggestion
MyNodeWithFlattenedMap {
```

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 11]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+    id: 'Foo',
+    time: 1,
+    `table.inner.key`: 'innerValue'
+}
+MyNodeWithMapFlattend {
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]:
```suggestion
MyNodeWithFlattenedMap {
```

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 12]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+    id: 'Bar',
+    time: 1,
+    `table.inner.key`: 'innerValue1'
+}
+----
+
+Now could happen that you have a Spark job like
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]:
```suggestion
Now could could into problematic situations like the following one:
```

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 13]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+----
+val data = Seq(
+  ("Foo", 1, Map("key.inner" -> Map("key" -> "innerValue"), "key" -> Map("inner.key" -> "value"))),
+  ("Bar", 1, Map("key.inner" -> Map("key" -> "innerValue1"), "key" -> Map("inner.key" -> "value1"))),
+).toDF("id", "time", "table")
+data.write
+  .mode(SaveMode.Append)
+  .format(classOf[DataSource].getName)
+  .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
+  .option("labels", ":MyNodeWithMapFlattend")
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]:
```suggestion
  .option("labels", ":MyNodeWithFlattenedMap")
```

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 14]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+  .save()
+----
+
+which leads to have duplicates keys while we flatten it, the Neo4j Spark connector informs you with a WARN message like this;
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]:
```suggestion
Since the resulting flattened keys are duplicated, the Neo4j Spark will pick one of the associated value in a non-deterministic way and inform you with a `WARN` message like the following one:
```

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 15]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+----
+The field `table` which has a map {key.inner -> {key=innerValue}, key -> {inner.key=value}}
+contains the following duplicated keys: [table.key.inner.key],
+you will loose information stored in these keys
+----
+
+Because the information that we'll store into Neo4j will be this:
+
+----
+MyNodeWithMapFlattend {
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]:
```suggestion
MyNodeWithFlattenedMap {
```

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 16]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+    id: 'Foo',
+    time: 1,
+    `table.key.inner.key`: 'innerValue'
+}
+MyNodeWithMapFlattend {
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]:
```suggestion
MyNodeWithFlattenedMap {
```

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 17]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+  .option("labels", ":MyNodeWithMapFlattend")
+  .save()
+----
+
+which leads to have duplicates keys while we flatten it, the Neo4j Spark connector informs you with a WARN message like this;
+
+----
+The field `table` which has a map {key.inner -> {key=innerValue}, key -> {inner.key=value}}
+contains the following duplicated keys: [table.key.inner.key],
+you will loose information stored in these keys
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]: see one of my first suggestion
if you accept it, you will need to change the message here

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 18]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+----
+
+Because the information that we'll store into Neo4j will be this:
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]: if it's a hash map, the iteration order is not guaranteed, so we could get `value[1]` or `innerValue[1]`, right?

File: common/src/main/scala/org/neo4j/spark/util/Neo4jImplicits.scala (hunk 5 above)
Comment (conker84) [reply common/src/main/scala/org/neo4j/spark/util/Neo4jImplicits.scala]: I used that name because there is already a `flatten` in scala GenericTraversableTemplate:
https://www.scala-lang.org/api/2.12.7/scala/collection/Iterable.html
We can think about another like `flatToDottedKeys` (this one no, is very ugly :smile:)

File: common/src/main/scala/org/neo4j/spark/service/MappingService.scala (hunk 6 above)
Comment (conker84) [reply common/src/main/scala/org/neo4j/spark/service/MappingService.scala]: Collect does exactly the same, for me more scala way instead of doing:

```
scalaMap.flattenKeys(field.name)
  .groupBy(identity)
  .filter(_.size > 1)
  .map(_.head)
```

File: common/src/test/scala/org/neo4j/spark/util/Neo4jImplicitsTest.scala (hunk 7 above)
Comment (conker84) [reply common/src/test/scala/org/neo4j/spark/util/Neo4jImplicitsTest.scala:178]: Yes correct, I wanted to test an ordered use-case to be sure that the behaviour is deterministic, when applicable.

File: common/src/main/scala/org/neo4j/spark/service/MappingService.scala (hunk 4 above)
Comment (conker84) [reply common/src/main/scala/org/neo4j/spark/service/MappingService.scala]: I thought about that, but I preferred to leave the implementation clean and then ad the business logic for checking duplicates in the Service

Comment (conker84) [reply common/src/main/scala/org/neo4j/spark/service/MappingService.scala]: Done

File: doc/docs/modules/ROOT/pages/writing.adoc (hunk 8 above)
Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: Done

File: doc/docs/modules/ROOT/pages/writing.adoc (hunk 9 above)
Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: Done

File: doc/docs/modules/ROOT/pages/writing.adoc (hunk 10 above)
Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: Done

File: doc/docs/modules/ROOT/pages/writing.adoc (hunk 11 above)
Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: Done

File: doc/docs/modules/ROOT/pages/writing.adoc (hunk 12 above)
Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: @fbiville maybe:
```suggestion
Now could fall into problematic situations like the following one:
```
?

File: doc/docs/modules/ROOT/pages/writing.adoc (hunk 13 above)
Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: Done

File: doc/docs/modules/ROOT/pages/writing.adoc (hunk 14 above)
Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: done

File: doc/docs/modules/ROOT/pages/writing.adoc (hunk 15 above)
Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: done

File: doc/docs/modules/ROOT/pages/writing.adoc (hunk 16 above)
Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: done

File: doc/docs/modules/ROOT/pages/writing.adoc (hunk 17 above)
Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: done

File: doc/docs/modules/ROOT/pages/writing.adoc (hunk 18 above)
Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: I extended the doc explaining that

File: common/src/main/scala/org/neo4j/spark/service/MappingService.scala [hunk 19]
```diff
@@ -122,10 +125,22 @@ class Neo4jWriteMappingStrategy(private val options: Neo4jOptions)
...
+              .collect { case (x, List(_,_,_*)) => x }
+            if (dupKeys.nonEmpty) {
```
Comment (fbiville) [inline common/src/main/scala/org/neo4j/spark/service/MappingService.scala]: actually, it's a pity to iterate over the map twice, could we move the duplicate check into `flattenMap`?

Comment (fbiville) [reply common/src/main/scala/org/neo4j/spark/service/MappingService.scala]: I'm also thinking that we could actually aggregate values in a collection when there are duplicates (with the caveat that the order is not deterministic is the initial map does not guarantee any iteration order)
since it's a breaking change, could we maybe allow this behavior only if a specific config flag is set (which would default to `false` -> the default value can change at the next major version)
wdyt?

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 20]
```diff
@@ -708,3 +708,76 @@ CREATE (n:Person{fullName: event.name + ' ' + event.surname, age: scriptResult[0
...
+    `table.inner.key`: 'innerValue'
+}
+MyNodeWithFlattenedMap {
+    id: 'Bar',
+    time: 1,
+    `table.inner.key`: 'innerValue1'
+}
+----
+
+Now could  into problematic situations like the following one:
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]: missing a word here ^^

Comment (conker84) [reply doc/docs/modules/ROOT/pages/writing.adoc]: done

File: common/src/main/scala/org/neo4j/spark/service/MappingService.scala (hunk 19 above)
Comment (conker84) [reply common/src/main/scala/org/neo4j/spark/service/MappingService.scala]: Let's eliminate logging because if we have a Dataframe with a column map with collisions with a count of 5b we risk printing the warning 5b times, which is not super...

File: common/src/test/scala/org/neo4j/spark/util/Neo4jImplicitsTest.scala [hunk 21]
```diff
@@ -178,6 +178,23 @@ class Neo4jImplicitsTest {
     Assert.assertEquals(expected, actual)
   }
 
+  @Test
+  def `should not handle collision by aggregating values`(): Unit = {
```
Comment (fbiville) [inline common/src/test/scala/org/neo4j/spark/util/Neo4jImplicitsTest.scala]:
```suggestion
def `should handle collision by aggregating values`(): Unit = {
```

File: doc/docs/modules/ROOT/pages/writing.adoc [hunk 22]
```diff
@@ -780,4 +774,40 @@ MyNodeWithFlattenedMap {
     time: 1,
     `table.key.inner.key`: 'innerValue1' // but it could be `value1` as the order is not guaranteed
 }
-----
\ No newline at end of file
+----
+
+=== Group duplicated keys to array of values
+
+You can use the option `schema.map.group.duplicate.keys` to avoid this problem, what the connector will do is to group all and only the values with duplicate keys into an array with all the values. The default value for the option is `false`.
```
Comment (fbiville) [inline doc/docs/modules/ROOT/pages/writing.adoc]:
```suggestion
You can use the option `schema.map.group.duplicate.keys` to avoid this problem. The connector will group all the values with the same keys into an array. The default value for the option is `false`.
```

File: spark-3/src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala [hunk 23]
```diff
@@ -1459,4 +1460,32 @@ class DataSourceWriterTSE extends SparkConnectorScalaBaseTSE {
...
+    val count: Long = SparkConnectorScalaSuiteIT.session().run(
+      """
+        |MATCH (n:MyNodeWithMapFlattend)
+        |WHERE (
+        | properties(n) = {id: 'Foo', time: 1, `table.key.inner.key`: ['innerValue', 'value']}
+        | OR properties(n) = {id: 'Bar', time: 1, `table.key.inner.key`: ['innerValue1', 'value1']}
+        |)
+        |RETURN count(n)
+        |""".stripMargin)
+      .peek()
```
Comment (fbiville) [inline spark-3/src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala]:
```suggestion
      .single()
```

Comment (fbiville) [reply spark-3/src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala]: same above

**Review by fbiville — APPROVED** [review]
