### PR TITLE
Fixes #170: add connection check on session creation

### LINKED ISSUE #170: Add connection check before reading and writing
When writing ad dataset to neo4j, if there is a driver misconfiguration we have this error:

```
org.apache.spark.SparkException: Writing job aborted.
  at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:92)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:260)
```

that doesn't say too much about why the writing failed. 
The actual error can be seen down the stack trace but I think it's easier to perform a connection test before trying to read or write data, this way we can show a better error message.

### PR DESCRIPTION
**Pull request by utnaf**
Fixes #170 and #199 

Added a connection check on session creation. Please tell me if there is a better way to check the connectivity.

This is the now error mentioned in #199 

Screenshot 2020-10-20 at 09 46 57

### CODE REVIEW

File: src/main/scala/org/neo4j/spark/util/Validations.scala [hunk 1]
```diff
@@ -129,4 +131,13 @@ object Validations {
       cache.close()
     }
   }
+
+  def validateConnection(session: Session): Unit = {
+    try {
+      session.run("EXPLAIN RETURN 1").consume()
```
Comment (moxious) [inline src/main/scala/org/neo4j/spark/util/Validations.scala:139]: Yep, that'd work.  Honestly you don't even need the explain, you could just roundtrip "something".   `RETURN 1` by itself would work, because it proves bi-directional communication and that the session is sensible, but either way is really fine, since you're not doing anything with the explain anyway

File: src/main/scala/org/neo4j/spark/util/Validations.scala [hunk 2]
```diff
@@ -15,6 +15,7 @@ object Validations {
     val cache = new DriverCache(neo4jOptions.connection, jobId)
     val schemaService = new SchemaService(neo4jOptions, cache)
     try {
+      validateConnection(cache.getOrCreate().session(neo4jOptions.session.toNeo4jSession))
```
Comment (moxious) [inline src/main/scala/org/neo4j/spark/util/Validations.scala:18]: watch out on semantics; this method is saying "get or create" - is session reuse possible here?  Because validateConnection closes the session.   Not sure if there's a code path to be concerned about there, but you have to throw away this session after validating the connection and you can't reuse it.

File: src/main/scala/org/neo4j/spark/util/Validations.scala [hunk 3]
```diff
@@ -94,6 +95,7 @@ object Validations {
     val cache = new DriverCache(neo4jOptions.connection, jobId)
     val schemaService = new SchemaService(neo4jOptions, cache)
```
Comment (moxious) [inline src/main/scala/org/neo4j/spark/util/Validations.scala:96]: A read is always tied to a set of options.

You have validateConnection called twice, in reader and in writer.   Rather than remembering to call it each time, if a SchemaService is tied to a set of options, you could put this into the initialization of the schemaservice.  Before you even get to the query, the schemaservice could validate connection for you, and the code would maybe be more dry, you don't have to remember to validate each time.

File: src/test/scala/org/neo4j/spark/DataSourceReaderNeo4j35xTSE.scala [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+import org.neo4j.driver.exceptions.ClientException
+
+object DataSourceReaderNeo4j35xTSE {
+  @BeforeClass
+  def checkNeo4jVersion() {
+    Assume.assumeTrue(TestUtil.neo4jVersion().startsWith("3.5"))
+  }
+}
+
+class DataSourceReaderNeo4j35xTSE extends SparkConnectorScalaBaseTSE {
```
Comment (moxious) [inline src/test/scala/org/neo4j/spark/DataSourceReaderNeo4j35xTSE.scala:15]: Another unit test scenario here which is the same problem but a different source, please add this and see if it behaves:

User connects to Neo4j 4.0 with databases (neo4j, system) and issues a query with `.option("database", "noexist")`.   Actually it's more likely they'll have like a typo in the database or whatever.

In 3.5 there is no valid database option, but in 4.0 you can always mess it up.  ;)

File: src/main/scala/org/neo4j/spark/util/Validations.scala (hunk 3 above)
Comment (utnaf) [reply src/main/scala/org/neo4j/spark/util/Validations.scala:96]: True what you said, also @conker84 made the same observation. But I would rather validate the connection in the Validator than validate in the SchemaService. Yep the code will be more dry, but if I need to find the connection validation, the validator would be the first file I would look into.

I don't really have a strong opinion on this. I could change it if the majority agrees it's better the other way, I was just explaining why it is how it is

File: src/main/scala/org/neo4j/spark/util/Validations.scala (hunk 2 above)
Comment (utnaf) [reply src/main/scala/org/neo4j/spark/util/Validations.scala:18]: `getOrCreate` is referred to the DriverCache, so what we're getting here is a driver instance and it's reusable. We can clear it up by chancing the `cache` variabile to `driverCache`

**Review by moxious — APPROVED** [review]
