### PR TITLE
fixes #531: Problem with datetime properties with null values

### LINKED ISSUE #531: Problem with datetime properties with null values
## Expected Behavior (Mandatory)

Create a dataframe based on the cypher query

## Actual Behavior (Mandatory)

Works fine on Databricks Runtime 9.1 LTS

Breaks on Databricks Runtime 12.2 LTS - Error Message->IOException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.ZonedDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
Caused by: InvalidDefinitionException: Java 8 date/time type `java.time.ZonedDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling

## How to Reproduce the Problem

Use any cypher query that returns more than one datetime, like: datetime(o.submittedDate) as submittedDateABC, o.isOnboardingSubmitted as isOnboardingSubmitted, datetime(o.triggeredDate) as triggeredDateABC, datetime(o.sentBackDate) as sentBackDateABC, o.finalActionTakenUsername as finalActionTakenUsername, datetime(o.onboardingFinalActionTakenDate) as onboardingFinalActionTakenDate, o.statusid as statusId

## Specifications (Mandatory)

Currently used versions

### Versions

- Spark: 3.3.2
- Scala: 2.12.15
- Neo4j: 4.4.15
- Neo4j Connector: 5.0.1

## Additional information

 Spark Cloud provider: Databricks 12.2LTS (https://docs.databricks.com/release-notes/runtime/12.2.html)

### PR DESCRIPTION
**Pull request by conker84**
fixes #531

### CODE REVIEW

File: spark-3/src/test/scala/org/neo4j/spark/DataSourceReaderTSE.scala [hunk 1]
```diff
@@ -1649,6 +1648,65 @@ class DataSourceReaderTSE extends SparkConnectorScalaBaseTSE {
...
+        .map(r => (r.getTimestamp(0), r.getString(1)))
+        .toSeq
+    )
+
+    val schema = StructType(Array(
+      StructField("first", DataTypes.TimestampType),
+      StructField("second", DataTypes.TimestampType),
+    ))
+    // dataFrameWithSchema must with the proper data type
+    val dataFrameWithSchema = ss.read.format(classOf[DataSource].getName)
```
Comment (fbiville) [inline spark-3/src/test/scala/org/neo4j/spark/DataSourceReaderTSE.scala:1745]: can you maybe extract this part into a second test?

Comment (conker84) [reply spark-3/src/test/scala/org/neo4j/spark/DataSourceReaderTSE.scala:1745]: Done

**Review by fbiville — APPROVED** [review]
