### PR TITLE
Fixes #179: Error writing node query generation with compound key

### LINKED ISSUE #179: Compound keys are used incorrectly in writing nodes by batch
Wrong cypher is getting generated when using a compound, aliased key for nodes.

Here's my spark code (pay particular attention to `loc_pk`)

```
# (Do complicated stuff to make a "locations" dataframe") 

locations_pk = ['LocationName', 'LocationType', 'FeatureID']
loc_pk = 'LocationName:name,LocationType:type,FeatureID:featureId'

locations.show()

locations.repartition(4).write \
  .format("org.neo4j.spark.DataSource") \
  .mode('overwrite') \
  .option("url", dbutils.widgets.get("url")) \
  .option("authentication.basic.username", dbutils.widgets.get("user")) \
  .option("authentication.basic.password", dbutils.widgets.get("password")) \
  .option("labels", 'Location') \
  .option("node.keys", loc_pk) \
  .option("batch.size", 20000) \
  .save()
```

Here's a picture on what the locations table looks like:
```
+------------------+------------+--------------------+----+--------+--------+---------+--------+---------+----+
|       GKGRECORDID|LocationType|        LocationName|ISO2|ADM1Code|ADM2Code|      Lat|     Lon|FeatureID|Last|
+------------------+------------+--------------------+----+--------+--------+---------+--------+---------+----+
|20200731154500-998|           2|Texas, United States|  US|    USTX|        |   31.106|-97.6475|       TX|4442|
|20200731154500-998|           1|               China|  CH|      CH|        |     35.0|   105.0|       CH|1633|
|20200731154500-998|           1|               China|  CH|      CH|        |     35.0|   105.0|       CH|2401|
|20200731154500-998|           1|               China|  CH|      CH|        |     35.0|   105.0|       CH|4675|
```

While running this and monitoring the Neo4j instance, the Cypher I see generated is this:

```
UNWIND $events AS event
MERGE (node:Location {LocationName: event.keys.LocationName, LocationType: event.keys.LocationType, FeatureID: event.keys.FeatureID})
SET node += event.properties
```

Remember: `loc_pk = 'LocationName:name,LocationType:type,FeatureID:featureId'`

The cypher I would EXPECT is this:

```
UNWIND $events AS event
MERGE (node:Location {name: event.keys.LocationName, type: event.keys.LocationType, featureId: event.keys.FeatureID})
SET node += event.properties
```

Basically -- the merge property list is named incorrectly.

### PR DESCRIPTION
**Pull request by utnaf**
Fixes #179 

Details in the issue.

Setup available in the issue will now generate this query:

```
UNWIND $events AS event
MERGE (node:Location {name: event.keys.LocationName, type: event.keys.LocationType, featureId: event.keys.FeatureID})
SET node += event.properties
```

Additional edits:
- removed `.show` calls in tests

### CODE REVIEW

**Review by moxious — COMMENTED** [review]
looks like the travis build is broken.  Will re-review when the build passes to make sure there aren't other issues present.

**Comment by utnaf** [comment]
> looks like the travis build is broken. Will re-review when the build passes to make sure there aren't other issues present.

Build is failing with scala 2.11, with 2.12 is passing.
But looks weird, I tried to run the tests on my machine with both versions of Scala and both of the builds are green. Can we try to retrigger?

**Comment by moxious** [comment]
I don't have a login into that travis system, I can't retrigger.

File: src/main/scala/org/neo4j/spark/service/Neo4jQueryService.scala [hunk 1]
```diff
@@ -17,6 +17,12 @@ class Neo4jQueryWriteStrategy(private val saveMode: SaveMode) extends Neo4jQuery
        |${options.query.value}
        |""".stripMargin
 
+  private def createPropsList(props: Map[String, String], prefix: String): String = {
+    props.map(key => {
+      s"${key._2.quote()}: $BATCH_VARIABLE.$prefix.${key._1.removeAlias().quote()}"
+    }).mkString(", ")
+  }
```
Comment (conker84) [inline src/main/scala/org/neo4j/spark/service/Neo4jQueryService.scala]: map to case class for better readibility:
```suggestion
  private def createPropsList(props: Map[String, String], prefix: String): String = {
    props
    .map(key => Neo4jSparkFieldMapping(key._2.quote(), key._1.removeAlias().quote()))
    .map(fieldMapping => {
      s"${fieldMapping.neo4jFieldName}: $BATCH_VARIABLE.$prefix.${fieldMapping.sparkFieldName}"
    }).mkString(", ")
  }
```

File: src/test/scala/org/neo4j/spark/Neo4jQueryServiceTest.scala [hunk 2]
```diff
@@ -216,4 +217,21 @@ class Neo4jQueryServiceTest {
       "AND rel.score = 12) " +
       "RETURN source, rel, target", query)
   }
+
+  @Test
+  def testCompoundKeys() = {
```
Comment (conker84) [inline src/test/scala/org/neo4j/spark/Neo4jQueryServiceTest.scala]: please add also a test for relationships

**Review by conker84 — CHANGES_REQUESTED** [review]
@utnaf thank you please check my comments

File: src/test/scala/org/neo4j/spark/Neo4jQueryServiceTest.scala [hunk 3]
```diff
@@ -216,4 +217,46 @@ class Neo4jQueryServiceTest {
...
+        |""".stripMargin, query)
+  }
+
+  @Test
+  def testCompoundKeysForRelationship() = {
+    val options: java.util.Map[String, String] = new java.util.HashMap[String, String]()
+    options.put(Neo4jOptions.URL, "bolt://localhost")
+    options.put("relationship", "BOUGHT")
+    options.put("relationship.source.labels", "Person")
+    options.put("relationship.source.node.keys", "FirstName:name")
```
Comment (conker84) [inline src/test/scala/org/neo4j/spark/Neo4jQueryServiceTest.scala]: please add a compound key for source and target

**Review by conker84 — CHANGES_REQUESTED** [review]
@utnaf please look at the comment

File: src/main/scala/org/neo4j/spark/service/MappingService.scala [hunk 4]
```diff
@@ -68,19 +68,19 @@ class Neo4jWriteMappingStrategy(private val options: Neo4jOptions)
   private def keysStrategyConsumer(): MappingBiConsumer = new MappingBiConsumer {
     override def accept(key: String, value: AnyRef): Unit = {
       if (options.relationshipMetadata.source.nodeKeys.contains(key)) {
-        sourceNodeMap.get(KEYS).put(key, value)
+        sourceNodeMap.get(KEYS).put(options.relationshipMetadata.source.nodeKeys.getOrElse(key, key), value)
       }
       else if (options.relationshipMetadata.source.nodeProps.contains(key)) {
-        sourceNodeMap.get(PROPERTIES).put(key, value)
+        sourceNodeMap.get(PROPERTIES).put(options.relationshipMetadata.source.nodeProps.getOrElse(key, key), value)
       }
```
Comment (conker84) [inline src/main/scala/org/neo4j/spark/service/MappingService.scala]: can we move this to a function like this?

```scala
private def addToNodeMap(nodeMap: Map[String, AnyRef], nodeMetadata: Neo4jNodeMetadata, key: String, value: AnyRef): Unit = {
      if (nodeMetadata.nodeKeys.contains(key)) {
        nodeMap.get(KEYS).put(nodeMetadata.nodeKeys.getOrElse(key, key), value)
      }
      if (nodeMetadata.nodeProps.contains(key)) {
        nodeMap.get(PROPERTIES).put(nodeMetadata.nodeProps.getOrElse(key, key), value)
      }
}
```

plus removing the else (also at line 82) we will allow to put the same properties in source and/or target and/or relationship, I think it would be useful.

**Review by conker84 — CHANGES_REQUESTED** [review]
@utnaf please look at the last comment, otherwise all looks good to me.

File: src/main/scala/org/neo4j/spark/service/MappingService.scala (hunk 4 above)
Comment (utnaf) [reply src/main/scala/org/neo4j/spark/service/MappingService.scala]: Ok for removing the else.

I don't extracting the function useful in this case, it will just move the existing code somewhere else, won't add any performance or readability improves. I think the code here is pretty straightforward. We can extract long lines into variables to make it more easy to read. Wdyt?

**Review by conker84 — APPROVED** [review]

**Comment by conker84** [comment]
I'm merging this, thank you @utnaf
