### PR TITLE
fixes #183: Better error messages

### LINKED ISSUE #183: Swallowed Exception (probably deadlock) on writing relationships
See screenshot.   I am intentionally writing a big relationship set with 6 partitions.  I *expect* it to fail, probably with deadlock exceptions because this particular relationship `(:Event)-[:THEME]->(:Theme)` has 1 million events and only 5 thousand themes, so each theme has a lot of relationships.

The problem is that this does fail, you just can't tell how.   Recommend we check for high-concurrency writes that are going to cause problems, and make sure that the deadlock or other exceptions get surfaced to the users so they have a chance to discover what's wrong.  I think this is potentially a common problem.

Screen Shot 2020-09-11 at 10 46 06 AM

### PR DESCRIPTION
**Pull request by utnaf**
fixes #183 

Compared to the example in the issue, now the same error will be logged as

```
Py4JJavaError: An error occurred while calling o116.save.
: org.neo4j.driver.exceptions.TransientException: Database 'neo4j' is unavailable.
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
	at org.neo4j.driver.internal.InternalTransaction.commit(InternalTransaction.java:39)
	at org.neo4j.driver.internal.InternalSession.lambda$transaction$4(InternalSession.java:154)
	at org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(ExponentialBackoffRetryLogic.java:102)
	at org.neo4j.driver.internal.InternalSession.transaction(InternalSession.java:146)
	at org.neo4j.driver.internal.InternalSession.writeTransaction(InternalSession.java:124)
	at org.neo4j.driver.internal.InternalSession.writeTransaction(InternalSession.java:118)
	at org.neo4j.spark.service.SchemaService.execute(SchemaService.scala:494)
	at org.neo4j.spark.writer.Neo4jDataSourceWriter.createWriterFactory(Neo4jDataSourceWriter.scala:29)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:55)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:260)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

Unfortunately I wasn't able to reproduce the issue in the integration tests. If you have any suggestions please write down a comment.

### CODE REVIEW

File: src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala [hunk 1]
```diff
@@ -706,6 +706,40 @@ class DataSourceWriterTSE extends SparkConnectorScalaBaseTSE {
     assertEquals("Guitar", res.get(3).getString(7))
   }
 
+// df: leaving this for the reviewers, wasn't able to recreate the deadlock issue
+//
+//  @Test
+//  def `should give better errors if transaction fails`(): Unit = {
```
Comment (conker84) [inline src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala]: @utnaf please uncomment it and add an `@Ignore("trying to recreate the deadlock issue")`

File: src/main/scala/org/neo4j/spark/writer/Neo4jDataWriter.scala [hunk 2]
```diff
@@ -40,7 +40,12 @@ class Neo4jDataWriter(jobId: String,
   override def write(record: InternalRow): Unit = {
     batch.add(mappingService.convert(record, structType))
     if (batch.size() == options.transactionMetadata.batchSize) {
-      writeBatch
+      try {
+        writeBatch()
+      }
+      catch {
+        case e: Exception => log.error(e.getMessage)
+      }
```
Comment (conker84) [inline src/main/scala/org/neo4j/spark/writer/Neo4jDataWriter.scala]: I think that this try/catch can be removed and managed here:

https://github.com/neo4j-contrib/neo4j-spark-connector/blob/fcdec5028cfc67762489e444022fdc490053e258/src/main/scala/org/neo4j/spark/writer/Neo4jDataWriter.scala#L52-L105

**Review by conker84 — CHANGES_REQUESTED** [review]

**Review by conker84 — APPROVED** [review]

**Comment by conker84** [comment]
@utnaf thank you!
